DELIMITER $$
CREATE TRIGGER PRODUCT_LIKE_AFTER_INSERT_TRIG
AFTER INSERT ON `PRODUCT_LIKE` FOR EACH ROW
begin
    UPDATE PRODUCT SET NUM_OF_LIKE = NUM_OF_LIKE + 1 WHERE ID = NEW.PRODUCT_ID;
END;
$$
DELIMITER ;