DELIMITER $$
CREATE TRIGGER PRODUCT_LIKE_AFTER_DELETE_TRIG
AFTER DELETE ON `PRODUCT_LIKE` FOR EACH ROW
begin
    UPDATE PRODUCT SET NUM_OF_LIKE = NUM_OF_LIKE - 1 WHERE ID = OLD.PRODUCT_ID;
END;
$$
DELIMITER ;