DELIMITER $$
CREATE TRIGGER PRODUCT_DETAIL_BEFORE_INSERT_TRIG
BEFORE INSERT ON `PRODUCT_DETAIL` FOR EACH ROW
begin
    SET @CUR_POS = (SELECT MAX(POSITION) FROM PRODUCT_DETAIL WHERE PRODUCT_ID = NEW.PRODUCT_ID);
    IF @CUR_POS IS NOT NULL THEN
		IF @CUR_POS > 9 THEN
			SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Maximum Number of Product Details per Product is 10!';
        END IF;
        SET NEW.POSITION = @CUR_POS + 1;
    ELSE
        SET NEW.POSITION = 1;
    END IF;
END;
$$
DELIMITER ;