DELIMITER $$
CREATE PROCEDURE DELETE_PRODUCT_DETAIL(productDetailId INT)
BEGIN
    SET @old_position := (SELECT POSITION FROM PRODUCT_DETAIL WHERE ID = productDetailId);
    IF @old_position IS NULL THEN
		SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'PRODUCT_DETAIL NOT FOUND!';
    END IF;
    DELETE FROM PRODUCT_DETAIL WHERE ID = productDetailId;
    UPDATE PRODUCT_DETAIL SET POSITION = POSITION - 1 WHERE POSITION > @old_position;
END
$$
DELIMITER ;