DELIMITER $$
CREATE TRIGGER COMMENT_LIKE_AFTER_DELETE_TRIG
AFTER DELETE ON `COMMENT_LIKE` FOR EACH ROW
begin
    UPDATE COMMENT SET NUM_OF_LIKE = NUM_OF_LIKE - 1 WHERE ID = OLD.COMMENT_ID;
END;
$$
DELIMITER ;
