DELIMITER $$
CREATE TRIGGER COMMENT_LIKE_AFTER_INSERT_TRIG
AFTER INSERT ON `COMMENT_LIKE` FOR EACH ROW
begin
    UPDATE COMMENT SET NUM_OF_LIKE = NUM_OF_LIKE + 1 WHERE ID = NEW.COMMENT_ID;
END;
$$
DELIMITER ;