CREATE TABLE COMMENT_LIKE
(
    ID INT NOT NULL AUTO_INCREMENT UNIQUE,
    COMMENT_ID INT NOT NULL,
    FROM_USER_ID VARCHAR(255) NOT NULL,
    CREATE_TIME TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

    PRIMARY KEY (ID),
    FOREIGN KEY (COMMENT_ID) REFERENCES COMMENT(ID) ON DELETE CASCADE,
    FOREIGN KEY (FROM_USER_ID) REFERENCES USER(USER_ID) ON DELETE CASCADE,
    INDEX(ID, COMMENT_ID, FROM_USER_ID, CREATE_TIME)
)