CREATE TABLE PRODUCT_DETAIL
(
    ID INT NOT NULL AUTO_INCREMENT UNIQUE,
    PRODUCT_ID INT NOT NULL,
    POSITION INT DEFAULT 0,
    DESCRIPTION VARCHAR(500),
    IMAGE_URL VARCHAR(255) NOT NULL,
    LAST_MODIFIED_TIME TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,

    PRIMARY KEY (ID),
    UNIQUE KEY (PRODUCT_ID, POSITION),
    FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCT(ID) ON DELETE CASCADE,
    INDEX(ID, PRODUCT_ID, POSITION, LAST_MODIFIED_TIME)
)