CREATE TABLE USER
(
    USER_ID VARCHAR(255) NOT NULL UNIQUE,
    EMAIL VARCHAR(50) NOT NULL,
    ENCRYPTED_PASSWORD VARCHAR(255) NOT NULL,
    FIRST_NAME VARCHAR(50) NOT NULL,
    LAST_NAME VARCHAR(50),
    CREATE_TIME TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    LAST_MODIFIED_TIME TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,

    PRIMARY KEY (USER_ID),
    INDEX(USER_ID, EMAIL)
)